### Simple 1-D array and slicing

In [5]:
import numpy as np

t = np.array([0, 1, 2, 3, 4, 5, 6])
print(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])  # start_index ~ end_index-1
print(t[:2], t[3:])

[0 1 2 3 4 5 6]
1
(7,)
0 1 6
[2 3 4] [4 5]
[0 1] [3 4 5 6]


### 2-D array

In [8]:
t = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])
print(t)
print(t.ndim) # rank
print(t.shape) # shape


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


### Shape, Rank, Axis in TensorFlow

In [49]:
import tensorflow as tf

sess = tf.InteractiveSession()

t = tf.constant([1,2,3,4])
tf.shape(t).eval(session=sess)

t = tf.constant([[1,2], 
                 [3,4]])
tf.shape(t).eval(session=sess)



array([2, 2], dtype=int32)

### Matmul vs multiply

In [20]:
mat1 = tf.constant([[1,2],[3,4]])
mat2 = tf.constant([[1], [2]])
print("mat1 shape", mat1.shape)
print("mat2 shape", mat2.shape)
tf.matmul(mat1, mat2).eval(session=sess)

(mat1*mat2).eval(session=sess) # broadcasting

mat1 shape (2, 2)
mat2 shape (2, 1)


array([[1, 2],
       [6, 8]], dtype=int32)

### Reduce mean/sum

In [22]:
tf.reduce_mean([1, 2], axis=0).eval(session=sess)

1

In [26]:
x = [[1., 2.], [3., 4.]]

tf.reduce_mean(x).eval(session=sess)
tf.reduce_mean(x, axis=0).eval(session=sess)
tf.reduce_mean(x, axis=1).eval(session=sess)
tf.reduce_mean(x, axis=-1).eval(session=sess)

array([ 1.5,  3.5], dtype=float32)

### Argmax

In [30]:
x = [[0, 1, 2], [2, 1, 0]]

tf.argmax(x, axis=0).eval(session=sess)
tf.argmax(x, axis=1).eval(session=sess)
tf.argmax(x, axis=-1).eval(session=sess) # same as 1

array([2, 0])

### Reshape

In [31]:
t = np.array([[ [0, 1, 2], [3, 4, 5]], 
              [ [6, 7, 8], [9, 10, 11]]])

t.shape

(2, 2, 3)

In [35]:
tf.reshape(t, shape=[-1, 3]).eval(session=sess) 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
tf.reshape(t, shape=[-1, 1, 3]).eval(session=sess) 

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [37]:
tf.squeeze([[0], [1], [2]]).eval(session=sess)

array([0, 1, 2], dtype=int32)

In [38]:
tf.expand_dims([0, 1, 2], 1).eval(session=sess)

array([[0],
       [1],
       [2]], dtype=int32)

In [40]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval(session=sess)

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [41]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3).eval(session=sess)
tf.reshape(t, shape=[-1, 3]).eval(session=sess)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

### Casting

In [42]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval(session=sess)


array([1, 2, 3, 4], dtype=int32)

In [50]:
tf.cast([True, False, 1==1, 0==1], tf.int32).eval()

array([1, 0, 1, 0], dtype=int32)

### Stack

In [51]:
x = [1,4]
y = [2,5]
z = [3,6]

tf.stack([x,y,z]).eval()


array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [55]:
tf.stack([x,y,z],axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

### Ones and Zeros like

In [56]:
x = [[0,1,2], [2,1,0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [57]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

### Zip

In [61]:
for x, y, z in zip([1,2,3], [4,5,6], [7,8,9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
