## Tutorial on Deep Network with ReLU

In [7]:
import tensorflow as tf
import numpy as np

x_data = np.array([[0,0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])


#
with tf.name_scope("layer1") as scope:
    W1 = tf.Variable(tf.random_uniform([2, 5], -1.0, 1.0), name="Weight1")
    b1 = tf.Variable(tf.zeros([5]), name="Bias1")
    L2 = tf.nn.relu(tf.matmul(X, W1) + b1)
    
    w1_hist = tf.summary.histogram("weights1", W1)
    b1_hist = tf.summary.histogram("biases1", b1)
    layer1_hist = tf.summary.histogram("layer1", L2)
    
with tf.name_scope("layer2") as scope:
    W2 = tf.Variable(tf.random_uniform([5, 4], -1.0, 1.0), name="Weight2")
    b2 = tf.Variable(tf.zeros([4]), name="Bias2")
    L3 = tf.nn.relu(tf.matmul(L2, W2) + b2)
    
    w2_hist = tf.summary.histogram("weights1", W2)
    b2_hist = tf.summary.histogram("biases1", b2)
    layer2_hist = tf.summary.histogram("layer1", L3)
    
with tf.name_scope("layer3") as scope:
    W3 = tf.Variable(tf.random_uniform([4, 4], -1.0, 1.0), name="Weight3")
    b3 = tf.Variable(tf.zeros([4]), name="Bias3")
    L4 = tf.nn.relu(tf.matmul(L3, W3) + b3)
    
    w3_hist = tf.summary.histogram("weights1", W3)
    b3_hist = tf.summary.histogram("biases1", b3)
    layer3_hist = tf.summary.histogram("layer1", L4)
    
with tf.name_scope("layer4") as scope:
    W4 = tf.Variable(tf.random_uniform([4, 4], -1.0, 1.0), name="Weight3")
    b4 = tf.Variable(tf.zeros([4]), name="Bias3")
    L5 = tf.nn.relu(tf.matmul(L4, W4) + b4)
        
with tf.name_scope("layer5") as scope:
    W5 = tf.Variable(tf.random_uniform([4, 4], -1.0, 1.0), name="Weight3")
    b5 = tf.Variable(tf.zeros([4]), name="Bias3")
    L6 = tf.nn.relu(tf.matmul(L5, W5) + b5)
        
with tf.name_scope("layer6") as scope:
    W6 = tf.Variable(tf.random_uniform([4, 4], -1.0, 1.0), name="Weight3")
    b6 = tf.Variable(tf.zeros([4]), name="Bias3")
    L7 = tf.nn.relu(tf.matmul(L6, W6) + b6)
    
with tf.name_scope("last") as scope:
    W7 = tf.Variable(tf.random_uniform([4, 1], -1.0, 1.0), name="Weight4")
    b7 = tf.Variable(tf.zeros([1]), name="Bias4")
    H  = tf.sigmoid(tf.matmul(L7, W7) + b7)
    
with tf.name_scope("cost") as scope:    
    cost = -tf.reduce_mean(Y * tf.log(H) + (1-Y)*tf.log(1-H))
    cost_summ = tf.summary.scalar("cost", cost)


with tf.name_scope("train") as scope:
        train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

predicted = tf.cast(H > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

with tf.Session() as sess:    
    merged_summary = tf.summary.merge_all()
    writer = tf.summary.FileWriter("./logs/xor_logs_r0_01")
    writer.add_graph(sess.graph)  # Show the graph
    
    sess.run(tf.global_variables_initializer())
    
    
    for step in range(50001):
        cost_val, W1_val, W2_val, _ = sess.run([cost, W1, W2, train], feed_dict = {X: x_data, Y: y_data})
        if step % 10000 == 0:
            print(step, cost_val, W1_val, W2_val)
            
    h, c, a = sess.run([H, predicted, accuracy], feed_dict = {X: x_data, Y: y_data})
    print(h, c, a)

0 0.695804 [[ 0.613177    0.65752822  0.00304974 -0.06903291 -0.26136369]
 [ 0.26692089 -0.6627562  -0.60580134 -0.44525242  0.96988976]] [[ 0.18295483 -0.91926956  0.50553226  0.84672451]
 [-0.15527514  0.46524906  0.79821903  0.87687379]
 [-0.90465909  0.28480244 -0.726982    0.02441068]
 [-0.93384647 -0.34278798  0.76770687 -0.28675365]
 [-0.76883435 -0.59093428  0.11928904  0.98940015]]
10000 0.00106637 [[ 1.42713511  0.32605517  0.00153462 -0.06903291  0.26808572]
 [ 0.41727743 -0.6627562  -0.60580134 -0.44525242  1.24461389]] [[ 0.27995691 -0.91926956  0.89335179  1.36300063]
 [-0.06912535  0.46524906  0.71530104  0.77405179]
 [-0.90465498  0.28480244 -0.7269842   0.02440594]
 [-0.93384647 -0.34278798  0.76770687 -0.28675365]
 [-0.85427004 -0.59093428  0.10971641  1.21243703]]
20000 0.000520183 [[ 1.43602502  0.32605517  0.00153462 -0.06903291  0.27491823]
 [ 0.42041475 -0.6627562  -0.60580134 -0.44525242  1.25192893]] [[ 0.27698845 -0.91926956  0.8987568   1.37103605]
 [-0.06912